// ── Transitional barrel — memory engine moved to @pipefx/brain-memory ──
// Keeps existing backend/workflows imports stable until Phase 4.7 rewire.
export {
  configureMemoryStore,
  getDatabase,
  closeDatabase,
  ensureProject,
  listProjects,
  getProject,
  createProject,
  updateProject,
  deleteProject,
  addKnowledge,
  getKnowledgeById,
  listKnowledge,
  searchKnowledge,
  updateKnowledge,
  forgetKnowledge,
  addProjectMemory,
  getProjectMemories,
  deleteProjectMemoryByIndex,
  startSession,
  getSession,
  endSession,
  updateSessionSummary,
  getRecentSessions,
  getLastSessionSummary,
  addInteraction,
  MemoryTaskManager,
  memoryTaskManager,
  setUserPreference,
  getUserPreference,
  getUserPreferences,
  deleteUserPreference,
  assembleProjectContext,
  assembleLegacyContext,
  createChatSession,
  appendChatMessage,
  getChatSession,
  getChatMessages,
  listChatSessions,
  deleteChatSession,
  updateChatSessionTitle,
  getLatestChatSession,
  chatSessionExists,
  migrateJsonProjects,
} from '@pipefx/brain-memory';
export type {
  ChatSessionDTO,
  ChatMessageDTO,
  ProjectDTO,
  KnowledgeDTO,
  KnowledgeInsert,
  KnowledgeCategory,
  KnowledgeSource,
  SessionDTO,
  TaskDTO,
  TaskStep,
  TaskStatus,
  TaskEvent,
  TaskRow,
  AssembledContext,
} from '@pipefx/brain-memory';
