packages:
  - 'packages/*'
  - 'apps/*'
  - 'data/example-skills'
allowBuilds:
  '@swc/core': true
  better-sqlite3: true
  esbuild: true
  msw: true
  nx: true
  protobufjs: true
  unrs-resolver: true
